CREATE TABLE users (
	user_id UUID NOT NULL,
	name varchar(255) NOT NULL,
	email varchar(255) NOT NULL,
	password varchar(255) NOT NULL,
	created timestamp(6) NOT NULL,
	modified timestamp(6) NOT NULL,
	last_login timestamp(6) NOT NULL,
	token varchar(255) NOT NULL,
	is_active boolean NOT NULL,
	PRIMARY KEY (user_id)
);

CREATE TABLE phones (
	phone_id integer GENERATED BY DEFAULT AS IDENTITY,
	user_id UUID NOT NULL,
	city_code varchar(255) NOT NULL,
	country_code varchar(255) NOT NULL, number varchar(255) NOT NULL,
	PRIMARY KEY (phone_id)
);

ALTER TABLE IF EXISTS phones ADD CONSTRAINT FKmg6d77tgqfen7n1g763nvsqe3 FOREIGN KEY (user_id) REFERENCES users;